function getLocations() {
	var data = [
					 "Dusseldorf, Germany",
					 "Frankfurt, Germany",
					 "Geneva, Switzerland",
					 "Copenhagen, Denmark",
					 "Sydney, Australia",
					 "Amsterdam, Netherlands",
					 "Wellington, New Zealand",
					 "Berlin, Germany",
					 "Bern, Switzerland",
					 "Toronto, Canada",
					 "Melbourne, Australia",
					 "Ottawa, Canada",
					 "Hamburg, Germany",
					 "Luxembourg, Luxembourg",
					 "Stockholm, Sweden",
					 "Brussels, Belgium",
					 "Perth, Australia",
					 "Montreal, Canada",
					 "Stuttgart, Germany",
					 "Nurnberg, Germany",
					 "Singapore, Singapore",
					 "Adelaide, Australia",
					 "San Francisco, United States",
					 "Canberra, Australia",
					 "Helsinki, Finland",
					 "Oslo, Norway",
					 "Calgary, Canada",
					 "Dublin, Ireland",
					 "Boston, United States",
					 "Honolulu, United States",
					 "Brisbane, Australia",
					 "Paris, France",
					 "Lyon, France",
					 "Barcelona, Spain",
					 "London, United Kingdom",
					 "Milan, Italy",
					 "Lisbon, Portugal",
					 "Chicago, United States",
					 "New York City, United States",
					 "Tokyo, Japan",
					 "Edinburgh, United Kingdom",
					 "Kobe, Japan",
					 "Seattle, United States",
					 "Los Angeles, United States",
					 "Yokohama, Japan",
					 "Washington, United States",
					 "Madrid, Spain",
					 "Birmingham, United Kingdom",
					 "Rome, Italy",
					 "Glasgow, United Kingdom",
					 "Pittsburgh, United States",
					 "Philadelphia, United States",
					 "Osaka, Japan",
					 "Aberdeen, United Kingdom",
					 "Leipzig, Germany",
					 "Minneapolis, United States",
					 "Nagoya, Japan",
					 "Dallas, United States",
					 "Belfast, United Kingdom",
					 "Houston, United States",
					 "Miami, United States",
					 "Atlanta, United States",
					 "St. Louis, United States",
					 "Prague, Czech Republic",
					 "Detroit, United States",
					 "Hong Kong",
					 "Pointe-a-Pitre, Guadeloupe",
					 "Seoul, South Korea",
					 "San Juan, Puerto Rico",
					 "Dubai, United Arab Emirates",
					 "Ljubljana, Slovenia",
					 "Budapest, Hungary",
					 "Montevideo, Uruguay",
					 "Vilnius, Lithuania",
					 "Warsaw, Poland",
					 "Abu Dhabi, United Arab Emirates",
					 "Bratislava, Slovakia",
					 "Port Louis, Mauritius",
					 "Taipei, Taiwan",
					 "Durban, South Africa",
					 "Kuala Lumpur, Malaysia",
					 "Athens, Greece",
					 "Limassol, Cyprus",
					 "Tallinn, Estonia",
					 "Riga, Latvia",
					 "Busan, South Korea",
					 "Cape Town, South Africa",
					 "Buenos Aires, Argentina",
					 "Santiago, Chile",
					 "Johannesburg, South Africa",
					 "Panama City, Panama",
					 "Victoria, Seychelles",
					 "Zagreb, Croatia",
					 "Wroclaw, Poland",
					 "Taichung, Taiwan",
					 "Shanghai, China",
					 "Bandar Seri Begawan, Brunei",
					 "Johor Bahru, Malaysia",
					 "Tel Aviv, Israel",
					 "San Jose, Costa Rica",
					 "Brasilia, Brazil",
					 "Muscat, Oman",
					 "Monterrey, Mexico",
					 "Bucharest, Romania",
					 "Doha, Qatar",
					 "Noumea, New Caledonia",
					 "Nassau, Bahamas",
					 "Tunis, Tunisia",
					 "Asuncion, Paraguay",
					 "Sofia, Bulgaria ",
					 "Rabat, Morocco",
					 "Rio de Janeiro, Brazil",
					 "Beijing, China",
					 "Guangzhou, China",
					 "Amman, Jordan",
					 "Sao Paulo, Brazil",
					 "Istanbul, Turkey",
					 "Lima, Peru",
					 "Kuwait City, Kuwait",
					 "Manaus, Brazil",
					 "Casablanca, Morocco",
					 "Mexico City, Mexico",
					 "Quito, Ecuador",
					 "Bangkok, Thailand",
					 "Bogota, Colombia",
					 "Windhoek, Namibia",
					 "Colombo, Sri Lanka",
					 "Manama, Bahrain",
					 "Chengdu, China",
					 "Santo Domingo, Dominican Republic",
					 "Manila, Philippines",
					 "Nanjing, China",
					 "Shenzhen, China",
					 "Hyderabad, India",
					 "Xi'an, China",
					 "Belgrade, Serbia",
					 "Jakarta, Indonesia",
					 "Gaborone, Botswana",
					 "Pune, India",
					 "Bangalore, India",
					 "Chongqing, China",
					 "Port of Spain, Trinidad and Tobago",
					 "Qingdao, China",
					 "Lusaka, Zambia",
					 "Chennai, India",
					 "Kingston, Jamaica",
					 "Guatemala City, Guatemala",
					 "Mumbai, India",
					 "Ho Chi Minh City, Vietnam",
					 "Hanoi, Vietnam",
					 "La Paz, Bolivia",
					 "Shenyang, China",
					 "Sarajevo, Bosnia-Herzegovina",
					 "Skopje, Macedonia",
					 "Kolkata, India",
					 "New Delhi, India",
					 "Dakar, Senegal",
					 "Libreville, Gabon",
					 "Riyadh, Saudi Arabia",
					 "Jeddah, Saudi Arabia",
					 "Accra, Ghana",
					 "Moscow, Russia",
					 "Jilin, China",
					 "Kampala, Uganda",
					 "Vientiane, Laos",
					 "Cairo, Egypt",
					 "Managua, Nicaragua",
					 "San Salvador, El Salvador",
					 "Saint Petersburg, Russia",
					 "Blantyre, Malawi",
					 "Almaty, Kazakhstan",
					 "Kiev, Ukraine",
					 "Maputo, Mozambique",
					 "Tirana, Albania",
					 "Beirut, Lebanon",
					 "Cotonou, Benin",
					 "Yerevan, Armenia",
					 "Banjul, Gambia",
					 "Nairobi, Kenya",
					 "Caracas, Venezuela",
					 "Tegucigalpa, Honduras",
					 "Algiers, Algeria",
					 "Tbilisi, Georgia",
					 "Djibouti, Djibouti",
					 "Minsk, Belarus",
					 "Kigali, Rwanda",
					 "Havana, Cuba",
					 "Islamabad, Pakistan",
					 "Yaounde, Cameroon",
					 "Phnom Penh, Cambodia",
					 "Douala, Cameroon",
					 "Baku, Azerbaijan",
					 "Dar es Salaam, Tanzania",
					 "Lahore, Pakistan",
					 "Luanda, Angola",
					 "Yangon, Myanmar",
					 "Karachi, Pakistan",
					 "Tehran, Iran",
					 "Lome, Togo",
					 "Tashkent, Uzbekistan",
					 "Abidjan, Côte d'Ivoire",
					 "Addis Ababa, Ethiopia",
					 "Ashkhabad, Turkmenistan",
					 "Harare, Zimbabwe",
					 "Bishkek, Kyrgyzstan",
					 "Lagos, Nigeria",
					 "Abuja, Nigeria",
					 "Dushanbe, Tajikistan",
					 "Dhaka, Bangladesh",
					 "Ouagadougou, Burkina Faso",
					 "Tripoli, Libya",
					 "Niamey, Niger",
					 "Antananarivo, Madagascar",
					 "Bamako, Mali",
					 "Nouakchott, Mauritania",
					 "Conakry, Guinea",
					 "Kinshasa, Congo, Democratic Republic of",
					 "Brazzaville, Congo, Republic of",
					 "Damascus, Syria",
					 "N'Djamena, Chad",
					 "Khartoum, Sudan",
					 "Port-au-Prince, Haiti",
					 "Sana'a, Yemen",
					 "Bangui, Central African Republic",
					 "Baghdad, Iraq"
                	];

	var clone = data.slice(0);
	return clone;
}